{{- range $name, $app := .Values.apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $name }}"
  labels:
    app: {{ $name }}
spec:
  type: {{ $app.service.type }}
  ports:
    - port: {{ $app.service.port }}
      targetPort: {{ $app.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $name }}

{{- end -}}