// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

import (
	"time"
)

const TableNameAdmin = "admins"

// Admin mapped from table <admins>
type Admin struct {
	ID          string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	DateCreated time.Time `gorm:"column:date_created;type:timestamp with time zone;not null" json:"date_created"`
	ChatID      string    `gorm:"column:chat_id;type:character varying(255);not null;default:NULL" json:"chat_id"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
