// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

import (
	"time"
)

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID          string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Sort        *int32    `gorm:"column:sort;type:integer" json:"sort"`
	DateCreated time.Time `gorm:"column:date_created;type:timestamp with time zone;not null" json:"date_created"`
	Content     *string   `gorm:"column:content;type:text" json:"content"`
	Image       *string   `gorm:"column:image;type:uuid" json:"image"`
	Type        *string   `gorm:"column:type;type:character varying(255);default:NULL" json:"type"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
