// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

const TableNameQuiz = "quizes"

// Quiz mapped from table <quizes>
type Quiz struct {
	ID     string `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	Region string `gorm:"column:region;type:character varying(255);not null;default:NULL" json:"region"`
}

// TableName Quiz's table name
func (*Quiz) TableName() string {
	return TableNameQuiz
}
