// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbmodels

import (
	"time"
)

const TableNameUserEventVisit = "user_event_visits"

// UserEventVisit mapped from table <user_event_visits>
type UserEventVisit struct {
	ID          string    `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	DateCreated time.Time `gorm:"column:date_created;type:timestamp with time zone;not null" json:"date_created"`
	UserChatID  string    `gorm:"column:user_chat_id;type:character varying(255);not null;default:NULL" json:"user_chat_id"`
}

// TableName UserEventVisit's table name
func (*UserEventVisit) TableName() string {
	return TableNameUserEventVisit
}
