// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID          string     `gorm:"column:id;type:uuid;primaryKey" json:"id"`
	DateCreated *time.Time `gorm:"column:date_created;type:timestamp with time zone" json:"date_created"`
	DateUpdated *time.Time `gorm:"column:date_updated;type:timestamp with time zone" json:"date_updated"`
	ProfilePic  *string    `gorm:"column:profile_pic;type:uuid" json:"profile_pic"`
	QrCode      *string    `gorm:"column:qr_code;type:uuid" json:"qr_code"`
	Role        *string    `gorm:"column:role;type:character varying(255);default:USER" json:"role"`
	ChatID      *string    `gorm:"column:chat_id;type:character varying(255)" json:"chat_id"`
	PhoneNumber *string    `gorm:"column:phone_number;type:character varying(255)" json:"phone_number"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
