nameOverride: "quree"
fullnameOverride: ""

imagePullSecrets:
  - name: quree-cr-creds

envSecretName: quree-env-secrets

serviceAccount:
  create: false
  name: ""
  automount: true
  annotations: {}

autoscaling:
  enabled: false

apps:
  tg-miniapp:
    replicaCount: 1
    image:
      repository: cr.yandex/crp5pkqt9sg0q8urtg3f/quree-tg-miniapp
      pullPolicy: IfNotPresent
      tag: "v1"
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: ClusterIP
      port: 80
      targetPort: 80
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/frontend-entry-points: http,https
        traefik.ingress.kubernetes.io/redirect-entry-point: https
        traefik.ingress.kubernetes.io/redirect-permanent: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: quree.maxnrm.monster
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: quree-manxmr-monster-tls
          hosts:
            - quree.maxnrm.monster
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    volumes: []
    volumeMounts: []
    nodeSelector: {}
    tolerations: []
    affinity: {}
  tg-update:
    replicaCount: 1
    image:
      repository: cr.yandex/crp5pkqt9sg0q8urtg3f/quree-tg-update
      pullPolicy: IfNotPresent
      tag: "v1"
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000
    ingress:
      enabled: false
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    volumes: []
    volumeMounts: []
    nodeSelector: {}
    tolerations: []
    affinity: {}
  tg-pusher:
    replicaCount: 1
    image:
      repository: cr.yandex/crp5pkqt9sg0q8urtg3f/quree-tg-pusher
      pullPolicy: IfNotPresent
      tag: "v1"
    podAnnotations: {}
    podLabels: {}
    podSecurityContext: {}
    securityContext: {}
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000
    ingress:
      enabled: false
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    volumes: []
    volumeMounts: []
    nodeSelector: {}
    tolerations: []
    affinity: {}