// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbquery

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"quree/internal/pg/dbmodels"
)

func newFile(db *gorm.DB, opts ...gen.DOOption) file {
	_file := file{}

	_file.fileDo.UseDB(db, opts...)
	_file.fileDo.UseModel(&dbmodels.File{})

	tableName := _file.fileDo.TableName()
	_file.ALL = field.NewAsterisk(tableName)
	_file.ID = field.NewString(tableName, "id")
	_file.Storage = field.NewString(tableName, "storage")
	_file.FilenameDisk = field.NewString(tableName, "filename_disk")
	_file.FilenameDownload = field.NewString(tableName, "filename_download")
	_file.Title = field.NewString(tableName, "title")
	_file.Type = field.NewString(tableName, "type")
	_file.Folder = field.NewString(tableName, "folder")
	_file.UploadedBy = field.NewString(tableName, "uploaded_by")
	_file.UploadedOn = field.NewTime(tableName, "uploaded_on")
	_file.ModifiedBy = field.NewString(tableName, "modified_by")
	_file.ModifiedOn = field.NewTime(tableName, "modified_on")
	_file.Charset = field.NewString(tableName, "charset")
	_file.Filesize = field.NewInt64(tableName, "filesize")
	_file.Width = field.NewInt32(tableName, "width")
	_file.Height = field.NewInt32(tableName, "height")
	_file.Duration = field.NewInt32(tableName, "duration")
	_file.Embed = field.NewString(tableName, "embed")
	_file.Description = field.NewString(tableName, "description")
	_file.Location = field.NewString(tableName, "location")
	_file.Tag = field.NewString(tableName, "tags")
	_file.Metadatum = field.NewString(tableName, "metadata")

	_file.fillFieldMap()

	return _file
}

type file struct {
	fileDo

	ALL              field.Asterisk
	ID               field.String
	Storage          field.String
	FilenameDisk     field.String
	FilenameDownload field.String
	Title            field.String
	Type             field.String
	Folder           field.String
	UploadedBy       field.String
	UploadedOn       field.Time
	ModifiedBy       field.String
	ModifiedOn       field.Time
	Charset          field.String
	Filesize         field.Int64
	Width            field.Int32
	Height           field.Int32
	Duration         field.Int32
	Embed            field.String
	Description      field.String
	Location         field.String
	Tag              field.String
	Metadatum        field.String

	fieldMap map[string]field.Expr
}

func (f file) Table(newTableName string) *file {
	f.fileDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f file) As(alias string) *file {
	f.fileDo.DO = *(f.fileDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *file) updateTableName(table string) *file {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.Storage = field.NewString(table, "storage")
	f.FilenameDisk = field.NewString(table, "filename_disk")
	f.FilenameDownload = field.NewString(table, "filename_download")
	f.Title = field.NewString(table, "title")
	f.Type = field.NewString(table, "type")
	f.Folder = field.NewString(table, "folder")
	f.UploadedBy = field.NewString(table, "uploaded_by")
	f.UploadedOn = field.NewTime(table, "uploaded_on")
	f.ModifiedBy = field.NewString(table, "modified_by")
	f.ModifiedOn = field.NewTime(table, "modified_on")
	f.Charset = field.NewString(table, "charset")
	f.Filesize = field.NewInt64(table, "filesize")
	f.Width = field.NewInt32(table, "width")
	f.Height = field.NewInt32(table, "height")
	f.Duration = field.NewInt32(table, "duration")
	f.Embed = field.NewString(table, "embed")
	f.Description = field.NewString(table, "description")
	f.Location = field.NewString(table, "location")
	f.Tag = field.NewString(table, "tags")
	f.Metadatum = field.NewString(table, "metadata")

	f.fillFieldMap()

	return f
}

func (f *file) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *file) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 21)
	f.fieldMap["id"] = f.ID
	f.fieldMap["storage"] = f.Storage
	f.fieldMap["filename_disk"] = f.FilenameDisk
	f.fieldMap["filename_download"] = f.FilenameDownload
	f.fieldMap["title"] = f.Title
	f.fieldMap["type"] = f.Type
	f.fieldMap["folder"] = f.Folder
	f.fieldMap["uploaded_by"] = f.UploadedBy
	f.fieldMap["uploaded_on"] = f.UploadedOn
	f.fieldMap["modified_by"] = f.ModifiedBy
	f.fieldMap["modified_on"] = f.ModifiedOn
	f.fieldMap["charset"] = f.Charset
	f.fieldMap["filesize"] = f.Filesize
	f.fieldMap["width"] = f.Width
	f.fieldMap["height"] = f.Height
	f.fieldMap["duration"] = f.Duration
	f.fieldMap["embed"] = f.Embed
	f.fieldMap["description"] = f.Description
	f.fieldMap["location"] = f.Location
	f.fieldMap["tags"] = f.Tag
	f.fieldMap["metadata"] = f.Metadatum
}

func (f file) clone(db *gorm.DB) file {
	f.fileDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f file) replaceDB(db *gorm.DB) file {
	f.fileDo.ReplaceDB(db)
	return f
}

type fileDo struct{ gen.DO }

type IFileDo interface {
	gen.SubQuery
	Debug() IFileDo
	WithContext(ctx context.Context) IFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFileDo
	WriteDB() IFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFileDo
	Not(conds ...gen.Condition) IFileDo
	Or(conds ...gen.Condition) IFileDo
	Select(conds ...field.Expr) IFileDo
	Where(conds ...gen.Condition) IFileDo
	Order(conds ...field.Expr) IFileDo
	Distinct(cols ...field.Expr) IFileDo
	Omit(cols ...field.Expr) IFileDo
	Join(table schema.Tabler, on ...field.Expr) IFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFileDo
	Group(cols ...field.Expr) IFileDo
	Having(conds ...gen.Condition) IFileDo
	Limit(limit int) IFileDo
	Offset(offset int) IFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFileDo
	Unscoped() IFileDo
	Create(values ...*dbmodels.File) error
	CreateInBatches(values []*dbmodels.File, batchSize int) error
	Save(values ...*dbmodels.File) error
	First() (*dbmodels.File, error)
	Take() (*dbmodels.File, error)
	Last() (*dbmodels.File, error)
	Find() ([]*dbmodels.File, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.File, err error)
	FindInBatches(result *[]*dbmodels.File, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*dbmodels.File) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFileDo
	Assign(attrs ...field.AssignExpr) IFileDo
	Joins(fields ...field.RelationField) IFileDo
	Preload(fields ...field.RelationField) IFileDo
	FirstOrInit() (*dbmodels.File, error)
	FirstOrCreate() (*dbmodels.File, error)
	FindByPage(offset int, limit int) (result []*dbmodels.File, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fileDo) Debug() IFileDo {
	return f.withDO(f.DO.Debug())
}

func (f fileDo) WithContext(ctx context.Context) IFileDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fileDo) ReadDB() IFileDo {
	return f.Clauses(dbresolver.Read)
}

func (f fileDo) WriteDB() IFileDo {
	return f.Clauses(dbresolver.Write)
}

func (f fileDo) Session(config *gorm.Session) IFileDo {
	return f.withDO(f.DO.Session(config))
}

func (f fileDo) Clauses(conds ...clause.Expression) IFileDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fileDo) Returning(value interface{}, columns ...string) IFileDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fileDo) Not(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fileDo) Or(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fileDo) Select(conds ...field.Expr) IFileDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fileDo) Where(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fileDo) Order(conds ...field.Expr) IFileDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fileDo) Distinct(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fileDo) Omit(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fileDo) Join(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fileDo) RightJoin(table schema.Tabler, on ...field.Expr) IFileDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fileDo) Group(cols ...field.Expr) IFileDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fileDo) Having(conds ...gen.Condition) IFileDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fileDo) Limit(limit int) IFileDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fileDo) Offset(offset int) IFileDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFileDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fileDo) Unscoped() IFileDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fileDo) Create(values ...*dbmodels.File) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fileDo) CreateInBatches(values []*dbmodels.File, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fileDo) Save(values ...*dbmodels.File) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fileDo) First() (*dbmodels.File, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.File), nil
	}
}

func (f fileDo) Take() (*dbmodels.File, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.File), nil
	}
}

func (f fileDo) Last() (*dbmodels.File, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.File), nil
	}
}

func (f fileDo) Find() ([]*dbmodels.File, error) {
	result, err := f.DO.Find()
	return result.([]*dbmodels.File), err
}

func (f fileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dbmodels.File, err error) {
	buf := make([]*dbmodels.File, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fileDo) FindInBatches(result *[]*dbmodels.File, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fileDo) Attrs(attrs ...field.AssignExpr) IFileDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fileDo) Assign(attrs ...field.AssignExpr) IFileDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fileDo) Joins(fields ...field.RelationField) IFileDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fileDo) Preload(fields ...field.RelationField) IFileDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fileDo) FirstOrInit() (*dbmodels.File, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.File), nil
	}
}

func (f fileDo) FirstOrCreate() (*dbmodels.File, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dbmodels.File), nil
	}
}

func (f fileDo) FindByPage(offset int, limit int) (result []*dbmodels.File, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fileDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fileDo) Delete(models ...*dbmodels.File) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fileDo) withDO(do gen.Dao) *fileDo {
	f.DO = *do.(*gen.DO)
	return f
}
