// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dbquery

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q              = new(Query)
	Admin          *admin
	File           *file
	Message        *message
	User           *user
	UserEventVisit *userEventVisit
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Admin = &Q.Admin
	File = &Q.File
	Message = &Q.Message
	User = &Q.User
	UserEventVisit = &Q.UserEventVisit
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Admin:          newAdmin(db, opts...),
		File:           newFile(db, opts...),
		Message:        newMessage(db, opts...),
		User:           newUser(db, opts...),
		UserEventVisit: newUserEventVisit(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Admin          admin
	File           file
	Message        message
	User           user
	UserEventVisit userEventVisit
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Admin:          q.Admin.clone(db),
		File:           q.File.clone(db),
		Message:        q.Message.clone(db),
		User:           q.User.clone(db),
		UserEventVisit: q.UserEventVisit.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Admin:          q.Admin.replaceDB(db),
		File:           q.File.replaceDB(db),
		Message:        q.Message.replaceDB(db),
		User:           q.User.replaceDB(db),
		UserEventVisit: q.UserEventVisit.replaceDB(db),
	}
}

type queryCtx struct {
	Admin          IAdminDo
	File           IFileDo
	Message        IMessageDo
	User           IUserDo
	UserEventVisit IUserEventVisitDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Admin:          q.Admin.WithContext(ctx),
		File:           q.File.WithContext(ctx),
		Message:        q.Message.WithContext(ctx),
		User:           q.User.WithContext(ctx),
		UserEventVisit: q.UserEventVisit.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
