name: Build tgbot-qr-scanner with nginx

on:
  push:
    tags: ['\d+.\d+.\d+']

jobs:
  build:
    runs-on: ubuntu-latest
    environment: maxnrm-dev
    steps:
      - uses: actions/checkout@v3

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: docker/login-action@v1
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: int128/kaniko-action@v1
        with:
          tags: ${{ vars.DOCKER_REGISTRY }}/curee-scan-miniapp:${{ env.RELEASE_VERSION }}

          executor: gcr.io/kaniko-project/executor:debug-perf
          kaniko-args: "--snapshot-mode=time --use-new-run --single-snapshot"
          push: true
          cache: false
